# Generated by Django 6.0.1 on 2026-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=6, unique=True, verbose_name='従業員ID')),
                ('staff_name', models.CharField(max_length=50, verbose_name='従業員名')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者権限')),
            ],
        ),
    ]
