# Generated by Django 6.0.1 on 2026-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, unique=True, verbose_name='見積番号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='確定フラグ')),
                ('total_price', models.IntegerField(default=0, verbose_name='見積時合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='本数')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='見積時単価')),
                ('subtotal', models.IntegerField(editable=False, verbose_name='小計')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='ステータス名')),
                ('is_fixed', models.BooleanField(default=False, help_text='このステータスの見積は編集不可', verbose_name='確定ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='項目名')),
                ('inch_size', models.IntegerField(blank=True, null=True, verbose_name='インチ')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
    ]
