# Generated by Django 6.0.1 on 2026-03-02 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge_type', models.CharField(choices=[('install', '交換工賃'), ('waste', '廃タイヤ'), ('valve', 'バルブ'), ('rft', 'RFT加算')], max_length=20)),
                ('unit_price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_inch', models.PositiveIntegerField()),
                ('max_inch', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('price_per_tire', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='ステータス名')),
                ('is_fixed', models.BooleanField(default=False, help_text='このステータスの見積は編集不可', verbose_name='確定ステータス')),
            ],
            options={
                'verbose_name': 'Estimate Status',
                'verbose_name_plural': 'Estimate Statuses',
            },
        ),
        migrations.CreateModel(
            name='OptionFeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム識別用コード（例: RFT_SURCHARGE）', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('rft', 'RFT加算'), ('waste_tire', '廃タイヤ処分'), ('valve', 'バルブ交換')], max_length=20)),
                ('unit_price', models.IntegerField()),
                ('per_tire', models.BooleanField(default=True)),
                ('requires_rft', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('take_home', '持ち帰り'), ('install', '交換作業')], max_length=20)),
                ('subtotal', models.IntegerField(default=0)),
                ('is_fixed', models.BooleanField(default=False, verbose_name='確定フラグ')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名（個人・会社）')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='車種')),
                ('estimate_number', models.CharField(max_length=50, unique=True, verbose_name='見積番号')),
                ('total_price', models.IntegerField(default=0, verbose_name='見積時合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='見積作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimates', to=settings.AUTH_USER_MODEL)),
                ('estimate_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='estimate.estimatestatus')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='本数')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='1本価格')),
                ('set_price', models.IntegerField(blank=True, null=True, verbose_name='4本特価')),
                ('subtotal', models.IntegerField(blank=True, null=True, verbose_name='タイヤ小計')),
                ('cost_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='estimate.costmaster')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimate.estimate')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='inventory.tire', verbose_name='タイヤ')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='作業本数')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('subtotal', models.IntegerField(verbose_name='小計')),
                ('cost_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimate.costmaster', verbose_name='諸費用')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='estimate.estimate', verbose_name='見積')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimate.estimateitem')),
            ],
        ),
    ]
