# Generated by Django 6.0.1 on 2026-02-22 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimate', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='見積作成者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimate.estimate'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='inventory.tire'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='estimate.estimatestatus'),
        ),
    ]
