# Generated by Django 6.0.1 on 2026-03-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatecharge',
            name='is_auto_generated',
            field=models.BooleanField(default=True, verbose_name='自動生成フラグ'),
        ),
        migrations.AddField(
            model_name='estimatecharge',
            name='is_manual_edited',
            field=models.BooleanField(default=False, help_text='数量を手動で変更した場合、自動計算の対象外になります', verbose_name='手動編集済み'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='work_quantity',
            field=models.IntegerField(default=4, help_text='工賃・廃タイヤ・バルブの計算に使用します。スペアなど車体への取付(交換)作業が不要・持ち帰り分が含まれる場合は、数量を減らしてください。', verbose_name='作業本数'),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='charge_type',
            field=models.CharField(choices=[('INSTALL', '基本工賃(バランス・脱着)'), ('waste', '廃タイヤ処分'), ('valve', 'ゴムバルブ交換'), ('rft', 'RFT加算'), ('OTHER', 'その他諸費用')], max_length=20, verbose_name='料金タイプ'),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='code',
            field=models.CharField(default='TEMP', help_text='RFT_FEE 等、システム識別用', max_length=50, unique=True, verbose_name='管理コード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='項目名'),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='set_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='4本特価(税込)'),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='unit_price',
            field=models.IntegerField(verbose_name='単価(税込)'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(blank=True, db_index=True, help_text='空のまま保存すると "EST-YYYYMMDD-001" 形式で自動採番されます', max_length=20, unique=True, verbose_name='見積番号'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='cost_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='estimate.chargemaster'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.IntegerField(default=4, verbose_name='購入本数'),
        ),
        migrations.AddConstraint(
            model_name='chargemaster',
            constraint=models.UniqueConstraint(fields=('charge_type', 'min_inch', 'max_inch', 'is_active'), name='unique_charge_active_range'),
        ),
    ]
