# Generated by Django 6.0.1 on 2026-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='status',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='見積時合計金額'),
        ),
    ]
