# Generated by Django 6.0.1 on 2026-03-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='set_price',
            field=models.IntegerField(default=0, help_text='4本購入時のセット価格', verbose_name='4本特価'),
        ),
    ]
