# Generated by Django 6.0.1 on 2026-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_estimatecharge_is_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='購入本数'),
        ),
    ]
