# Generated by Django 6.0.1 on 2026-03-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_estimateitem_set_price'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatecharge',
            name='cost_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimate.costmaster', verbose_name='諸費用'),
        ),
        migrations.AlterField(
            model_name='estimatecharge',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='estimate.estimate', verbose_name='見積'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.IntegerField(verbose_name='本数'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='set_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='4本特価'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='タイヤ小計'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='inventory.tire', verbose_name='タイヤ'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='1本価格'),
        ),
    ]
