# Generated by Django 6.0.1 on 2026-02-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='vehicle_name',
            field=models.CharField(default='', max_length=100, verbose_name='車種'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='顧客名（個人・会社）'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='estimate.estimatestatus'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
