# Generated by Django 6.0.1 on 2026-04-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_alter_estimateitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='position',
            field=models.CharField(choices=[('all', '前後共通'), ('front', '前輪'), ('rear', '後輪')], default='all', max_length=10, verbose_name='装着位置'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='estimate.estimatestatus'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='purchase_type',
            field=models.CharField(choices=[('take_home', '持ち帰り'), ('install', '交換作業')], default='install', max_length=20, verbose_name='購入区分'),
        ),
    ]
