# Generated by Django 6.0.1 on 2026-04-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_estimateitem_position_alter_estimate_estimate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='position',
            field=models.CharField(choices=[('all', '前後同サイズ'), ('front', '前輪用'), ('rear', '後輪用')], default='all', max_length=10, verbose_name='装着位置'),
        ),
    ]
