# Generated by Django 6.0.1 on 2026-01-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='メーカー')),
                ('brand', models.CharField(max_length=50, verbose_name='ブランド')),
                ('pattern', models.CharField(max_length=50, verbose_name='パターン')),
                ('size', models.CharField(max_length=20, verbose_name='サイズ表記')),
                ('width', models.PositiveIntegerField(verbose_name='幅(mm)')),
                ('aspect_ratio', models.PositiveIntegerField(verbose_name='偏平率(%)')),
                ('rim', models.PositiveIntegerField(verbose_name='インチ(inch)')),
                ('road_index', models.CharField(blank=True, max_length=10, verbose_name='ロードインデックス')),
                ('speed_symbol', models.CharField(blank=True, max_length=5, verbose_name='速度記号')),
                ('price_single', models.PositiveIntegerField(verbose_name='1本価格')),
                ('price_set', models.PositiveIntegerField(verbose_name='4本特価')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='店内全在庫')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='予約在庫')),
                ('reorder_quantity', models.IntegerField(default=4, help_text='在庫がこの本数を下回ったら発注アラートを出します', verbose_name='発注点')),
                ('status', models.CharField(choices=[('in_stock', '在庫あり'), ('backorder', '入荷待ち'), ('orderable', '取寄可能')], default='in_stock', max_length=20, verbose_name='在庫状態')),
                ('tire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.tire')),
            ],
        ),
    ]
