# Generated by Django 6.0.1 on 2026-02-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TireStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30, verbose_name='ステータス名')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='商品コード')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='メーカー')),
                ('brand', models.CharField(max_length=50, verbose_name='ブランド')),
                ('size_raw', models.CharField(max_length=20, verbose_name='サイズ')),
                ('unit_price', models.IntegerField(verbose_name='1本単価')),
                ('set_price', models.IntegerField(blank=True, null=True, verbose_name='4本特価')),
                ('reorder_point', models.IntegerField(blank=True, null=True, verbose_name='発注点')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='在庫数量')),
                ('description', models.TextField(blank=True, help_text='検索・見積画面に表示される説明文', verbose_name='商品紹介文')),
                ('tire_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.tirestatus')),
            ],
        ),
    ]
