# Generated by Django 6.0.1 on 2026-02-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='price_set',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='price_single',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='rim',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='road_index',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='speed_symbol',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='width',
        ),
        migrations.AddField(
            model_name='tire',
            name='product_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='商品コード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='set_price',
            field=models.IntegerField(default=0, verbose_name='4本特価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='size_raw',
            field=models.CharField(default='', max_length=20, verbose_name='サイズ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='在庫数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='1本価格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_quantity',
            field=models.IntegerField(verbose_name='発注点'),
        ),
    ]
