# Generated by Django 6.0.1 on 2026-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='size_raw',
            field=models.CharField(max_length=50, verbose_name='サイズ'),
        ),
    ]
