# Generated by Django 6.0.1 on 2026-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_tire_aspect_ratio_remove_tire_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_point',
            field=models.IntegerField(default=4, verbose_name='発注点'),
        ),
        migrations.AddField(
            model_name='tire',
            name='load_index',
            field=models.CharField(blank=True, max_length=10, verbose_name='荷重指数'),
        ),
        migrations.AddField(
            model_name='tire',
            name='speed_symbol',
            field=models.CharField(blank=True, max_length=5, verbose_name='速度記号'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='総在庫数'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='set_price',
            field=models.IntegerField(verbose_name='4本価格'),
        ),
    ]
