# Generated by Django 6.0.1 on 2026-04-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_tire_size_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ブランド名')),
                ('comment', models.TextField(blank=True, verbose_name='ブランド特徴コメント')),
            ],
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tire',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='tire',
            name='brand_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tires', to='inventory.brand'),
        ),
    ]
