# Generated by Django 6.0.1 on 2026-04-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_alter_tire_brand_alter_tire_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='仕入れ値'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
