# Generated by Django 6.0.1 on 2026-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='load_index',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='speed_symbol',
        ),
        migrations.AddField(
            model_name='tire',
            name='reorder_point',
            field=models.IntegerField(default=4, verbose_name='定数'),
        ),
        migrations.AddField(
            model_name='tire',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='実在庫'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_point',
            field=models.IntegerField(default=4, verbose_name='定数'),
        ),
    ]
