# Generated by Django 6.0.1 on 2026-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_tire_load_index_remove_tire_speed_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='仕入れ値'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='set_price',
            field=models.IntegerField(verbose_name='4本特価'),
        ),
    ]
