# Generated by Django 6.0.1 on 2026-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_tire_cost_price_alter_tire_brand_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='is_runflat',
            field=models.BooleanField(default=False),
        ),
    ]
