# Generated by Django 6.0.1 on 2026-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tire_purchase_price_alter_tire_set_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, unique=True, verbose_name='見積番号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tire',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='stock_qty',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
