# Generated by Django 6.0.1 on 2026-04-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tire_is_runflat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=4, verbose_name='数量')),
                ('status', models.CharField(choices=[('DRAFT', '仮発注'), ('CONFIRMED', '確定'), ('CANCELLED', '取消')], default='DRAFT', max_length=10, verbose_name='状態')),
                ('cost_price_at_order', models.IntegerField(blank=True, null=True, verbose_name='発注時仕入れ値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発注日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tire', verbose_name='タイヤ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='発注者')),
            ],
            options={
                'verbose_name': '発注',
                'verbose_name_plural': '発注一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
