# Generated by Django 6.0.1 on 2026-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='reserved_qty',
            field=models.IntegerField(default=0, verbose_name='予約確定数'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='reorder_point',
            field=models.IntegerField(default=0, verbose_name='発注点'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='実在庫'),
        ),
    ]
