# Generated by Django 6.0.1 on 2026-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
    ]
